import type { Volunteer } from "./types";

export const volunteerData: Volunteer[] = [
  {
    id: "vol-anuj-avhad",
    name: "Anuj Avhad",
    role: "Campaign Manager",
    status: "Active",
    workloadStatus: "Stable",
    phone: "+91 98 0000 1101",
    whatsapp: "+91 98 0000 1101",
    village: "Sinnar Town",
    ward: "Central Ward",
    booth: "Command Desk",
    zone: "Sinnar Urban",
    coordinator: "Candidate Desk",
    skills: ["War room coordination", "Daily review", "Escalation handling"],
    assignedCampaigns: ["Command Review", "Volunteer Mobilization", "Daily Brief"],
    activeTasks: 5,
    completedTasks: 28,
    verifiedTasks: 22,
    overdueTasks: 0,
    capacity: 64,
    performanceScore: 88,
    attendanceScore: 92,
    activityScore: 83,
    reportQualityScore: 86,
    lastActivity: "Reviewed booth coverage notes",
    nextDeadline: "2026-06-19",
    reportsSubmitted: 18,
    doorVisits: 22,
    callsMade: 84,
    meetingsAttended: 17,
    issuesReported: 5,
    opponentActivityReported: 2
  },
  {
    id: "vol-priya-kale",
    name: "Priya Kale",
    role: "Constituency Coordinator",
    status: "On Ground",
    workloadStatus: "Busy",
    phone: "+91 98 0000 1102",
    whatsapp: "+91 98 0000 1102",
    village: "Sinnar Town",
    ward: "North Ward",
    booth: "Booth 102",
    zone: "Sinnar Urban",
    coordinator: "Anuj Avhad",
    reportsToId: "vol-anuj-avhad",
    skills: ["Field routing", "Volunteer training", "Call verification"],
    assignedCampaigns: ["Youth Contact Drive", "Urban Ward Sweep"],
    activeTasks: 11,
    completedTasks: 42,
    verifiedTasks: 35,
    overdueTasks: 1,
    capacity: 82,
    performanceScore: 84,
    attendanceScore: 88,
    activityScore: 86,
    reportQualityScore: 79,
    lastActivity: "Submitted ward sweep checklist",
    nextDeadline: "2026-06-18",
    reportsSubmitted: 24,
    doorVisits: 68,
    callsMade: 142,
    meetingsAttended: 11,
    issuesReported: 9,
    opponentActivityReported: 3
  },
  {
    id: "vol-sachin-jadhav",
    name: "Sachin Jadhav",
    role: "Ward Coordinator",
    status: "On Ground",
    workloadStatus: "Overloaded",
    phone: "+91 98 0000 1103",
    whatsapp: "+91 98 0000 1103",
    village: "Musalgaon",
    ward: "Musalgaon Ward",
    booth: "Booth 071",
    zone: "Musalgaon Belt",
    coordinator: "Priya Kale",
    reportsToId: "vol-priya-kale",
    skills: ["Booth follow-up", "Farmer listening", "Coordinator reporting"],
    assignedCampaigns: ["Farmer Evidence Drive", "Booth Gap Closure", "Follow-up Calls"],
    activeTasks: 17,
    completedTasks: 31,
    verifiedTasks: 24,
    overdueTasks: 4,
    capacity: 96,
    performanceScore: 74,
    attendanceScore: 79,
    activityScore: 82,
    reportQualityScore: 70,
    lastActivity: "Flagged overdue farmer follow-ups",
    nextDeadline: "2026-06-18",
    reportsSubmitted: 16,
    doorVisits: 91,
    callsMade: 96,
    meetingsAttended: 9,
    issuesReported: 14,
    opponentActivityReported: 5
  },
  {
    id: "vol-meena-pawar",
    name: "Meena Pawar",
    role: "Village Coordinator",
    status: "Active",
    workloadStatus: "Stable",
    phone: "+91 98 0000 1104",
    whatsapp: "+91 98 0000 1104",
    village: "Dubere",
    ward: "Dubere Ward",
    booth: "Booth 084",
    zone: "Women SHG Belt",
    coordinator: "Priya Kale",
    reportsToId: "vol-priya-kale",
    skills: ["SHG outreach", "Women forum coordination", "Issue intake"],
    assignedCampaigns: ["Women SHG Forums", "Household Follow-up"],
    activeTasks: 7,
    completedTasks: 36,
    verifiedTasks: 30,
    overdueTasks: 0,
    capacity: 58,
    performanceScore: 91,
    attendanceScore: 94,
    activityScore: 88,
    reportQualityScore: 90,
    lastActivity: "Updated SHG forum attendance",
    nextDeadline: "2026-06-20",
    reportsSubmitted: 22,
    doorVisits: 76,
    callsMade: 71,
    meetingsAttended: 14,
    issuesReported: 7,
    opponentActivityReported: 1
  },
  {
    id: "vol-rohit-wagh",
    name: "Rohit Wagh",
    role: "Booth Coordinator",
    status: "Active",
    workloadStatus: "Needs Follow-up",
    phone: "+91 98 0000 1105",
    whatsapp: "+91 98 0000 1105",
    village: "Wavi",
    ward: "Wavi Ward",
    booth: "Booth 090",
    zone: "Wavi Cluster",
    coordinator: "Meena Pawar",
    reportsToId: "vol-meena-pawar",
    skills: ["Booth list checking", "Family mapping", "WhatsApp follow-up"],
    assignedCampaigns: ["Booth Verification", "Household Mapping"],
    activeTasks: 9,
    completedTasks: 21,
    verifiedTasks: 18,
    overdueTasks: 2,
    capacity: 73,
    performanceScore: 72,
    attendanceScore: 76,
    activityScore: 68,
    reportQualityScore: 74,
    lastActivity: "Missed two household verification updates",
    nextDeadline: "2026-06-18",
    reportsSubmitted: 11,
    doorVisits: 47,
    callsMade: 63,
    meetingsAttended: 6,
    issuesReported: 4,
    opponentActivityReported: 2
  },
  {
    id: "vol-nilesh-kale",
    name: "Nilesh Kale",
    role: "Youth Volunteer",
    status: "On Ground",
    workloadStatus: "Busy",
    phone: "+91 98 0000 1106",
    whatsapp: "+91 98 0000 1106",
    village: "Sinnar Town",
    ward: "MIDC Ward",
    booth: "Booth 102",
    zone: "Sinnar Urban",
    coordinator: "Rohit Wagh",
    reportsToId: "vol-rohit-wagh",
    skills: ["Youth outreach", "Sports network", "Call reminders"],
    assignedCampaigns: ["Youth Contact Drive", "First-Time Voter Calls"],
    activeTasks: 12,
    completedTasks: 26,
    verifiedTasks: 20,
    overdueTasks: 1,
    capacity: 84,
    performanceScore: 81,
    attendanceScore: 82,
    activityScore: 87,
    reportQualityScore: 73,
    lastActivity: "Called first-time voter list",
    nextDeadline: "2026-06-19",
    reportsSubmitted: 13,
    doorVisits: 38,
    callsMade: 159,
    meetingsAttended: 8,
    issuesReported: 6,
    opponentActivityReported: 2
  },
  {
    id: "vol-sunita-more",
    name: "Sunita More",
    role: "Women Outreach Volunteer",
    status: "New",
    workloadStatus: "Stable",
    phone: "+91 98 0000 1107",
    whatsapp: "+91 98 0000 1107",
    village: "Devpur",
    ward: "Devpur Ward",
    booth: "Booth 117",
    zone: "Devpur Belt",
    coordinator: "Meena Pawar",
    reportsToId: "vol-meena-pawar",
    skills: ["Women outreach", "Healthcare issue logging"],
    assignedCampaigns: ["Women SHG Forums"],
    activeTasks: 3,
    completedTasks: 4,
    verifiedTasks: 3,
    overdueTasks: 0,
    capacity: 32,
    performanceScore: 68,
    attendanceScore: 74,
    activityScore: 59,
    reportQualityScore: 62,
    lastActivity: "Completed onboarding call",
    nextDeadline: "2026-06-21",
    reportsSubmitted: 3,
    doorVisits: 12,
    callsMade: 21,
    meetingsAttended: 2,
    issuesReported: 2,
    opponentActivityReported: 0
  },
  {
    id: "vol-vishal-shinde",
    name: "Vishal Shinde",
    role: "Field Volunteer",
    status: "On Leave",
    workloadStatus: "Needs Follow-up",
    phone: "+91 98 0000 1108",
    whatsapp: "+91 98 0000 1108",
    village: "Pangri",
    ward: "Pangri Ward",
    booth: "Booth 066",
    zone: "Pangri Farmers Belt",
    coordinator: "Sachin Jadhav",
    reportsToId: "vol-sachin-jadhav",
    skills: ["Door visits", "Farmer issue notes"],
    assignedCampaigns: ["Farmer Evidence Drive"],
    activeTasks: 6,
    completedTasks: 19,
    verifiedTasks: 15,
    overdueTasks: 2,
    capacity: 44,
    performanceScore: 66,
    attendanceScore: 52,
    activityScore: 64,
    reportQualityScore: 68,
    lastActivity: "Leave marked by coordinator",
    nextDeadline: "2026-06-22",
    reportsSubmitted: 8,
    doorVisits: 43,
    callsMade: 34,
    meetingsAttended: 4,
    issuesReported: 5,
    opponentActivityReported: 1
  },
  {
    id: "vol-aarti-gaikwad",
    name: "Aarti Gaikwad",
    role: "Data Volunteer",
    status: "Active",
    workloadStatus: "Stable",
    phone: "+91 98 0000 1109",
    whatsapp: "+91 98 0000 1109",
    village: "Nandur Shingote",
    ward: "Nandur Ward",
    booth: "Booth 121",
    zone: "Nandur Belt",
    coordinator: "Priya Kale",
    reportsToId: "vol-priya-kale",
    skills: ["CSV cleanup", "Report validation", "Source tagging"],
    assignedCampaigns: ["Data Quality Review", "Booth Verification"],
    activeTasks: 8,
    completedTasks: 44,
    verifiedTasks: 40,
    overdueTasks: 0,
    capacity: 61,
    performanceScore: 89,
    attendanceScore: 90,
    activityScore: 79,
    reportQualityScore: 94,
    lastActivity: "Validated booth import rows",
    nextDeadline: "2026-06-20",
    reportsSubmitted: 27,
    doorVisits: 9,
    callsMade: 46,
    meetingsAttended: 6,
    issuesReported: 3,
    opponentActivityReported: 1
  },
  {
    id: "vol-ganesh-borse",
    name: "Ganesh Borse",
    role: "Booth Coordinator",
    status: "Inactive",
    workloadStatus: "Needs Follow-up",
    phone: "+91 98 0000 1110",
    whatsapp: "+91 98 0000 1110",
    village: "Baragaon Pimpri",
    ward: "Pimpri Ward",
    booth: "Booth 134",
    zone: "Baragaon Belt",
    coordinator: "Sachin Jadhav",
    reportsToId: "vol-sachin-jadhav",
    skills: ["Booth contact list", "Local route knowledge"],
    assignedCampaigns: ["Booth Gap Closure"],
    activeTasks: 4,
    completedTasks: 11,
    verifiedTasks: 7,
    overdueTasks: 3,
    capacity: 18,
    performanceScore: 48,
    attendanceScore: 41,
    activityScore: 46,
    reportQualityScore: 53,
    lastActivity: "No update since last review",
    nextDeadline: "2026-06-18",
    reportsSubmitted: 5,
    doorVisits: 24,
    callsMade: 18,
    meetingsAttended: 2,
    issuesReported: 4,
    opponentActivityReported: 1
  }
];

export const volunteerRoles = Array.from(new Set(volunteerData.map((volunteer) => volunteer.role)));
export const volunteerZones = Array.from(new Set(volunteerData.map((volunteer) => volunteer.zone)));
export const volunteerBooths = Array.from(new Set(volunteerData.map((volunteer) => volunteer.booth)));
export const volunteerCoordinators = Array.from(new Set(volunteerData.map((volunteer) => volunteer.coordinator)));
