export type VerificationStatus =
  | "unverified"
  | "needs_verification"
  | "partially_verified"
  | "verified"
  | "disputed"
  | "stale";

export type EvidenceType =
  | "image"
  | "video"
  | "document"
  | "news_article"
  | "affidavit"
  | "election_result"
  | "field_report"
  | "social_post"
  | "court_record"
  | "speech"
  | "interview"
  | "internal_note";

export type InboxStatus = "new" | "triage" | "assigned" | "verifying" | "verified" | "rejected" | "archived";

export type TaskStatus = "open" | "assigned" | "in_progress" | "blocked" | "completed" | "cancelled";

export type Priority = "critical" | "high" | "medium" | "low";

export type RelationshipKind = "supportive" | "neutral" | "opposed" | "unknown";

export type SentimentPolarity = "positive" | "neutral" | "negative" | "mixed";

export type EntityType =
  | "candidate"
  | "opponent"
  | "party"
  | "political_organization"
  | "person"
  | "influencer"
  | "village"
  | "booth"
  | "community"
  | "issue"
  | "political_event"
  | "media_mention"
  | "intelligence_signal"
  | "political_risk"
  | "political_opportunity"
  | "evidence_item"
  | "source_record"
  | "research_task"
  | "user"
  | "role"
  | "audit_log"
  | "relationship_edge"
  | "sentiment_record"
  | "intelligence_report"
  | "recommendation"
  | "task"
  | "ownership_record"
  | "owner"
  | "team"
  | "territory_assignment"
  | "reporting_line"
  | "escalation_chain"
  | "ownership_history"
  | "review_schedule"
  | "visit_record"
  | "visit_outcome"
  | "visit_participant"
  | "visit_follow_up"
  | "visit_report"
  | "visit_checklist"
  | "conversation_log"
  | "follow_up_record"
  | "promise_record"
  | "intelligence_timeline_event"
  | "verification_request"
  | "approval_request"
  | "evidence_review"
  | "audit_log_entry"
  | "voter_record"
  | "household_record"
  | "influencer_record"
  | "import_batch"
  | "campaign_organization"
  | "campaign_role"
  | "role_responsibility"
  | "team_member"
  | "team_member_assignment"
  | "zone"
  | "sector"
  | "village_cluster"
  | "booth_cluster"
  | "community_desk"
  | "volunteer_team"
  | "volunteer_team_member"
  | "coverage_record"
  | "roster"
  | "shift_assignment"
  | "campaign_hierarchy"
  | "coverage_gap"
  | "workload_metric"
  | "organization_unit"
  | "constituency_profile"
  | "constituency_zone"
  | "constituency_watchlist_item"
  | "constituency_report";
