import type {
  ApprovalRequest,
  AuditLogEntry,
  ConversationLog,
  EvidenceReview,
  FollowUpRecord,
  ImportBatch,
  InfluencerRecord,
  IntelligenceTimelineEvent,
  ManagedSentimentRecord,
  PromiseRecord,
  VerificationRequest,
  VoterRecord,
  HouseholdRecord
} from "./types";

const now = "2026-06-12T09:00:00+05:30";

function base(id: string, sourceIds: string[], confidenceScore = 50) {
  return {
    id,
    createdAt: "2026-06-12T08:00:00+05:30",
    updatedAt: now,
    createdBy: "user-intel-lead",
    updatedBy: "user-intel-lead",
    verificationStatus: "needs_verification" as const,
    confidenceScore,
    sourceIds,
    notes: "Priority 1 foundation mock record. Keep internal until source, evidence, verification, and approval are complete."
  };
}

export const conversationLogs: ConversationLog[] = [
  {
    ...base("conv-pangri-farmers", ["src-field-reports"], 56),
    conversationTitle: "Pangri farmer irrigation conversation",
    conversationType: "issue_verification",
    relatedVisitId: "visit-pangri-irrigation",
    relatedEntityType: "issue",
    relatedEntityId: "issue-irrigation-pangri",
    villageId: "v-pangri",
    boothId: "booth-pangri-001",
    communityId: "comm-farmers",
    householdId: "",
    influencerId: "",
    issueId: "issue-irrigation-pangri",
    riskId: "",
    opportunityId: "",
    participants: ["Farmer Cell Lead", "Pangri Sector Coordinator", "Farmer group cluster"],
    personSpokenTo: "Farmer group cluster",
    spokenBy: "Farmer Cell Lead",
    date: "2026-06-09",
    time: "10:10",
    location: "Pangri irrigation belt",
    summary: "Farmers repeated concerns about water release timing and asked for a visible follow-up from Uday Sangle's team.",
    keyPoints: "Water release timing, crop loss, trust gap, evidence packet requirement.",
    objectionsRaised: "Campaign visits should not become empty promises.",
    issuesRaised: "Irrigation timing and crop-loss support.",
    promisesMade: "Evidence packet and candidate-side review.",
    sentimentObserved: "frustrated_but_open",
    supportObserved: "lean_support_after_visit",
    politicalAlignment: "persuadable",
    followUpRequired: true,
    nextAction: "Create promise and follow-up task for farmer evidence packet.",
    ownerId: "owner-farmer-cell",
    approvalStatus: "pending_review",
    evidenceIds: ["ev-visit-pangri-photos"]
  },
  {
    ...base("conv-youth-midc", ["src-field-reports"], 60),
    conversationTitle: "MIDC youth employment listening conversation",
    conversationType: "community_meeting",
    relatedVisitId: "visit-midc-youth-listening",
    relatedEntityType: "political_opportunity",
    relatedEntityId: "opp-youth-employment",
    villageId: "v-sinnar-town",
    boothId: "booth-midc-001",
    communityId: "comm-youth",
    householdId: "",
    influencerId: "inf-youth-organizer",
    issueId: "",
    riskId: "",
    opportunityId: "opp-youth-employment",
    participants: ["Youth Desk Lead", "Youth organizer cluster", "First-time voter group"],
    personSpokenTo: "Youth organizer cluster",
    spokenBy: "Youth Desk Lead",
    date: "2026-06-10",
    time: "19:05",
    location: "MIDC belt, Sinnar Town",
    summary: "Youth participants asked for training, job access, sports facilities, and a second listening circle.",
    keyPoints: "Employment, training, sports, fast follow-up.",
    objectionsRaised: "Doubt that leaders continue youth work after elections.",
    issuesRaised: "Local employment access and sports ground maintenance.",
    promisesMade: "Prepare youth issue sheet and second listening circle.",
    sentimentObserved: "positive",
    supportObserved: "support_improved",
    politicalAlignment: "supportive",
    followUpRequired: true,
    nextAction: "Convert listening notes into youth action brief.",
    ownerId: "owner-youth-desk",
    approvalStatus: "pending_review",
    evidenceIds: ["ev-visit-youth-notes"]
  }
];

export const followUpRecords: FollowUpRecord[] = [
  {
    ...base("follow-pangri-evidence", ["src-field-reports"], 54),
    title: "Complete Pangri irrigation evidence packet",
    followUpType: "issue_evidence",
    relatedEntityType: "issue",
    relatedEntityId: "issue-irrigation-pangri",
    relatedVisitId: "visit-pangri-irrigation",
    relatedConversationId: "conv-pangri-farmers",
    relatedPromiseId: "promise-pangri-evidence-review",
    villageId: "v-pangri",
    boothId: "booth-pangri-001",
    householdId: "",
    influencerId: "",
    communityId: "comm-farmers",
    ownerId: "owner-farmer-cell",
    assignedTeamId: "team-farmer-cell",
    dueDate: "2026-06-13",
    priority: "high",
    status: "assigned",
    reason: "Farmers asked for visible proof-backed follow-up.",
    expectedOutcome: "Evidence packet ready for candidate farmer concern review.",
    actualOutcome: "",
    completionNotes: "",
    evidenceRequired: true,
    evidenceIds: ["ev-visit-pangri-photos"],
    approvalStatus: "pending_review"
  },
  {
    ...base("follow-musalgaon-backup-owner", ["src-field-reports"], 44),
    title: "Assign Musalgaon backup owner",
    followUpType: "ownership_escalation",
    relatedEntityType: "ownership_record",
    relatedEntityId: "own-v-musalgaon",
    relatedVisitId: "visit-musalgaon-owner-recovery",
    relatedConversationId: "",
    relatedPromiseId: "",
    villageId: "v-musalgaon",
    boothId: "booth-musalgaon-001",
    householdId: "",
    influencerId: "",
    communityId: "comm-farmers",
    ownerId: "owner-campaign-manager",
    assignedTeamId: "team-war-room",
    dueDate: "2026-06-11",
    priority: "critical",
    status: "overdue",
    reason: "Ownership overload is creating stale field intelligence.",
    expectedOutcome: "Backup owner assigned and escalation closed.",
    actualOutcome: "",
    completionNotes: "",
    evidenceRequired: true,
    evidenceIds: ["ev-visit-musalgaon-followup"],
    approvalStatus: "changes_requested"
  }
];

export const promiseRecords: PromiseRecord[] = [
  {
    ...base("promise-pangri-evidence-review", ["src-field-reports"], 55),
    promiseTitle: "Pangri farmer evidence review",
    promiseType: "campaign_follow_up",
    promiseMadeBy: "Farmer Cell Lead",
    promiseMadeTo: "Farmer group cluster",
    relatedEntityType: "issue",
    relatedEntityId: "issue-irrigation-pangri",
    relatedVisitId: "visit-pangri-irrigation",
    relatedConversationId: "conv-pangri-farmers",
    villageId: "v-pangri",
    boothId: "booth-pangri-001",
    communityId: "comm-farmers",
    householdId: "",
    influencerId: "",
    issueId: "issue-irrigation-pangri",
    promiseDescription: "Prepare evidence packet and candidate-side review before the next farmer meeting.",
    datePromised: "2026-06-09",
    dueDate: "2026-06-16",
    priority: "high",
    politicalImpact: 72,
    trustImpact: 80,
    status: "assigned",
    ownerId: "owner-farmer-cell",
    escalationOwnerId: "owner-campaign-manager",
    fulfillmentEvidenceIds: [],
    evidenceIds: ["ev-visit-pangri-photos"],
    approvalStatus: "pending_review",
    completionNotes: ""
  },
  {
    ...base("promise-youth-second-circle", ["src-field-reports"], 58),
    promiseTitle: "Second youth employment listening circle",
    promiseType: "community_commitment",
    promiseMadeBy: "Youth Desk Lead",
    promiseMadeTo: "Youth organizer cluster",
    relatedEntityType: "political_opportunity",
    relatedEntityId: "opp-youth-employment",
    relatedVisitId: "visit-midc-youth-listening",
    relatedConversationId: "conv-youth-midc",
    villageId: "v-sinnar-town",
    boothId: "booth-midc-001",
    communityId: "comm-youth",
    householdId: "",
    influencerId: "inf-youth-organizer",
    issueId: "",
    promiseDescription: "Schedule a second circle and convert youth concerns into a visible action brief.",
    datePromised: "2026-06-10",
    dueDate: "2026-06-18",
    priority: "high",
    politicalImpact: 78,
    trustImpact: 76,
    status: "in_progress",
    ownerId: "owner-youth-desk",
    escalationOwnerId: "owner-war-room-lead",
    fulfillmentEvidenceIds: [],
    evidenceIds: ["ev-visit-youth-notes"],
    approvalStatus: "pending_review",
    completionNotes: ""
  }
];

export const intelligenceTimelineEvents: IntelligenceTimelineEvent[] = [
  {
    ...base("timeline-visit-pangri-completed", ["src-field-reports"], 58),
    eventTitle: "Pangri irrigation visit completed",
    eventType: "visit_completed",
    entityType: "visit_record",
    entityId: "visit-pangri-irrigation",
    eventDate: "2026-06-09",
    eventTime: "11:05",
    actorId: "owner-farmer-cell",
    villageId: "v-pangri",
    boothId: "booth-pangri-001",
    communityId: "comm-farmers",
    severity: "high",
    summary: "Visit moved support and sentiment upward but requires evidence review before public use.",
    previousValue: "support 51 / risk 65",
    newValue: "support 58 / risk 57",
    relatedRecordUrl: "/visits/visit-pangri-irrigation",
    evidenceIds: ["ev-visit-pangri-photos"],
    approvalStatus: "pending_review"
  },
  {
    ...base("timeline-musalgaon-escalated", ["src-field-reports"], 46),
    eventTitle: "Musalgaon ownership escalation created",
    eventType: "risk_escalated",
    entityType: "ownership_record",
    entityId: "own-v-musalgaon",
    eventDate: "2026-06-11",
    eventTime: "09:00",
    actorId: "owner-war-room-lead",
    villageId: "v-musalgaon",
    boothId: "booth-musalgaon-001",
    communityId: "comm-farmers",
    severity: "critical",
    summary: "Ownership gap remains unresolved and threatens field execution.",
    previousValue: "assigned owner overloaded",
    newValue: "backup owner required",
    relatedRecordUrl: "/ownership-registry/own-v-musalgaon",
    evidenceIds: ["ev-visit-musalgaon-followup"],
    approvalStatus: "changes_requested"
  }
];

export const verificationRequests: VerificationRequest[] = [
  {
    ...base("verify-pangri-visit", ["src-field-reports"], 58),
    recordType: "visit_record",
    recordId: "visit-pangri-irrigation",
    submittedBy: "owner-farmer-cell",
    submittedAt: "2026-06-09T12:00:00+05:30",
    evidenceIds: ["ev-visit-pangri-photos"],
    verificationNotes: "Need location proof and two independent confirmations before candidate brief.",
    verifierId: "owner-war-room-lead",
    verificationDecision: "pending",
    nextVerificationStep: "Upload timestamped photos and confirm farmer names internally.",
    approvalStatus: "pending_review"
  },
  {
    ...base("verify-form20", ["src-source-map"], 80),
    recordType: "research_task",
    recordId: "research-form20",
    submittedBy: "user-intel-lead",
    submittedAt: "2026-06-10T09:30:00+05:30",
    evidenceIds: ["ev-eci-form20"],
    verificationNotes: "Official Form 20 is still pending.",
    verifierId: "owner-war-room-lead",
    verificationDecision: "needs_more_evidence",
    nextVerificationStep: "Collect official ECI Form 20.",
    approvalStatus: "changes_requested"
  }
];

export const approvalRequests: ApprovalRequest[] = [
  {
    ...base("approval-youth-brief", ["src-field-reports"], 58),
    approvalTitle: "Approve youth action brief for internal circulation",
    approvalType: "AI recommendation approval",
    recordType: "promise_record",
    recordId: "promise-youth-second-circle",
    submittedBy: "owner-youth-desk",
    submittedAt: "2026-06-12T08:20:00+05:30",
    approverId: "owner-campaign-manager",
    status: "pending",
    decisionNote: "Check privacy and source notes before sending to field teams.",
    sourceIds: ["src-field-reports"],
    evidenceIds: ["ev-visit-youth-notes"]
  },
  {
    ...base("approval-musalgaon-owner-change", ["src-field-reports"], 44),
    approvalTitle: "Approve Musalgaon backup owner assignment",
    approvalType: "Ownership change approval",
    recordType: "ownership_record",
    recordId: "own-v-musalgaon",
    submittedBy: "owner-war-room-lead",
    submittedAt: "2026-06-11T10:00:00+05:30",
    approverId: "owner-campaign-manager",
    status: "escalated",
    decisionNote: "Campaign manager review required due overdue village ownership.",
    sourceIds: ["src-field-reports"],
    evidenceIds: ["ev-visit-musalgaon-followup"]
  }
];

export const evidenceReviews: EvidenceReview[] = [
  {
    ...base("evidence-review-pangri-photos", ["src-field-reports"], 48),
    evidenceTitle: "Pangri irrigation visit field photos",
    evidenceType: "image",
    filePathOrUrl: "pending-upload",
    relatedRecordType: "visit_record",
    relatedRecordId: "visit-pangri-irrigation",
    submittedBy: "owner-farmer-cell",
    dateCaptured: "2026-06-09",
    dateUploaded: "2026-06-10",
    sourceId: "src-field-reports",
    evidenceQualityScore: 52,
    reviewerId: "owner-war-room-lead",
    reviewNotes: "Need timestamp and locality confirmation.",
    approvalStatus: "pending_review",
    evidenceIds: ["ev-visit-pangri-photos"]
  },
  {
    ...base("evidence-review-youth-notes", ["src-field-reports"], 52),
    evidenceTitle: "MIDC youth listening field notes",
    evidenceType: "field_report",
    filePathOrUrl: "internal-note-pending",
    relatedRecordType: "conversation_log",
    relatedRecordId: "conv-youth-midc",
    submittedBy: "owner-youth-desk",
    dateCaptured: "2026-06-10",
    dateUploaded: "2026-06-10",
    sourceId: "src-field-reports",
    evidenceQualityScore: 60,
    reviewerId: "owner-war-room-lead",
    reviewNotes: "Good internal signal; participant details must remain protected.",
    approvalStatus: "pending_review",
    evidenceIds: ["ev-visit-youth-notes"]
  }
];

export const auditLogEntries: AuditLogEntry[] = [
  {
    ...base("audit-entry-pangri-score", ["src-field-reports"], 58),
    eventType: "score_changed",
    entityType: "visit_record",
    entityId: "visit-pangri-irrigation",
    actorId: "owner-farmer-cell",
    actorRole: "Community Lead",
    timestamp: "2026-06-09T11:05:00+05:30",
    previousValue: "support 51, sentiment 52, risk 65",
    newValue: "support 58, sentiment 59, risk 57",
    changeReason: "Field visit completed and observations entered.",
    source: "Internal field report",
    ipDevicePlaceholder: "Device/IP capture pending",
    approvalId: "",
    verificationId: "verify-pangri-visit",
    severity: "high",
    evidenceIds: ["ev-visit-pangri-photos"],
    approvalStatus: "pending_review"
  },
  {
    ...base("audit-entry-musalgaon-escalation", ["src-field-reports"], 44),
    eventType: "record_escalated",
    entityType: "ownership_record",
    entityId: "own-v-musalgaon",
    actorId: "owner-war-room-lead",
    actorRole: "War Room",
    timestamp: "2026-06-11T09:00:00+05:30",
    previousValue: "owner overloaded",
    newValue: "escalated to campaign manager",
    changeReason: "Backup owner not assigned before due date.",
    source: "Ownership Registry",
    ipDevicePlaceholder: "Device/IP capture pending",
    approvalId: "approval-musalgaon-owner-change",
    verificationId: "",
    severity: "critical",
    evidenceIds: ["ev-visit-musalgaon-followup"],
    approvalStatus: "changes_requested"
  }
];

export const voterRecords: VoterRecord[] = [
  {
    ...base("voter-sample-youth-001", ["src-field-reports"], 42),
    voterName: "Youth voter sample 001",
    voterId: "pending-electoral-roll-link",
    age: 24,
    gender: "Not recorded",
    villageId: "v-sinnar-town",
    boothId: "booth-midc-001",
    householdId: "",
    communityIds: ["comm-youth"],
    segmentIds: ["first_time_or_young_voter"],
    occupation: "Industrial worker / needs verification",
    phonePlaceholder: "Protected",
    supportStatus: "lean_support",
    persuasionScore: 72,
    turnoutProbability: 61,
    influenceLevel: "peer_influence",
    primaryIssueIds: ["issue-youth-employment"],
    relationshipOwnerId: "owner-youth-desk",
    lastContactDate: "2026-06-10",
    nextAction: "Invite to second youth employment listening circle.",
    approvalStatus: "draft",
    evidenceIds: ["ev-visit-youth-notes"]
  },
  {
    ...base("voter-sample-farmer-001", ["src-field-reports"], 40),
    voterName: "Farmer voter sample 001",
    voterId: "pending-electoral-roll-link",
    age: 51,
    gender: "Not recorded",
    villageId: "v-pangri",
    boothId: "booth-pangri-001",
    householdId: "",
    communityIds: ["comm-farmers"],
    segmentIds: ["farmer_issue_voter"],
    occupation: "Farmer",
    phonePlaceholder: "Protected",
    supportStatus: "persuadable",
    persuasionScore: 68,
    turnoutProbability: 58,
    influenceLevel: "household_influencer",
    primaryIssueIds: ["issue-irrigation-pangri"],
    relationshipOwnerId: "owner-farmer-cell",
    lastContactDate: "2026-06-09",
    nextAction: "Close irrigation evidence follow-up.",
    approvalStatus: "draft",
    evidenceIds: ["ev-visit-pangri-photos"]
  }
];

export const householdRecords: HouseholdRecord[] = [
  {
    ...base("household-high-influence-001", ["src-field-reports"], 35),
    householdName: "Devpur high influence household cluster",
    villageId: "v-devpur",
    boothId: "",
    addressLocality: "Devpur locality pending verification",
    familySize: 6,
    eligibleVoters: 4,
    primaryInfluencerId: "",
    communityIds: ["comm-women"],
    supportStatus: "unknown",
    persuasionScore: 50,
    turnoutRisk: 60,
    keyIssues: ["ownership gap", "relationship mapping"],
    assignedVolunteerId: "",
    relationshipOwnerId: "owner-war-room-lead",
    visitHistoryIds: ["visit-devpur-household-cluster"],
    conversationIds: [],
    promiseIds: [],
    followUpIds: [],
    approvalStatus: "draft",
    evidenceIds: []
  },
  {
    ...base("household-pangri-farmer-cluster", ["src-field-reports"], 44),
    householdName: "Pangri farmer household cluster",
    villageId: "v-pangri",
    boothId: "booth-pangri-001",
    addressLocality: "Pangri irrigation belt",
    familySize: 5,
    eligibleVoters: 3,
    primaryInfluencerId: "",
    communityIds: ["comm-farmers"],
    supportStatus: "persuadable",
    persuasionScore: 64,
    turnoutRisk: 52,
    keyIssues: ["irrigation", "crop loss"],
    assignedVolunteerId: "owner-farmer-cell",
    relationshipOwnerId: "owner-farmer-cell",
    visitHistoryIds: ["visit-pangri-irrigation"],
    conversationIds: ["conv-pangri-farmers"],
    promiseIds: ["promise-pangri-evidence-review"],
    followUpIds: ["follow-pangri-evidence"],
    approvalStatus: "pending_review",
    evidenceIds: ["ev-visit-pangri-photos"]
  }
];

export const influencerRecords: InfluencerRecord[] = [
  {
    ...base("influencer-youth-organizer-record", ["src-field-reports"], 48),
    influencerName: "Youth organizer cluster",
    category: "youth_sports",
    villageId: "v-sinnar-town",
    communityIds: ["comm-youth"],
    boothIds: ["booth-midc-001"],
    occupation: "Youth network organizer",
    organizations: ["Sahyadri-linked network"],
    estimatedReach: 650,
    influenceScore: 68,
    politicalAlignment: "supportive",
    supportStatus: "lean_support",
    relationshipStrength: 66,
    relationshipOwnerId: "owner-youth-desk",
    lastContactDate: "2026-06-10",
    nextAction: "Schedule second youth listening circle.",
    riskLevel: "medium",
    opportunityLevel: "high",
    approvalStatus: "pending_review",
    evidenceIds: ["ev-visit-youth-notes"]
  },
  {
    ...base("influencer-farmer-rep-record", ["src-field-reports"], 42),
    influencerName: "Pangri farmer representative cluster",
    category: "farmer_issue_leader",
    villageId: "v-pangri",
    communityIds: ["comm-farmers"],
    boothIds: ["booth-pangri-001"],
    occupation: "Farmer representative",
    organizations: ["Local water users"],
    estimatedReach: 420,
    influenceScore: 63,
    politicalAlignment: "persuadable",
    supportStatus: "swing",
    relationshipStrength: 50,
    relationshipOwnerId: "owner-farmer-cell",
    lastContactDate: "2026-06-09",
    nextAction: "Complete evidence-backed candidate follow-up.",
    riskLevel: "high",
    opportunityLevel: "high",
    approvalStatus: "draft",
    evidenceIds: ["ev-visit-pangri-photos"]
  }
];

export const managedSentimentRecords: ManagedSentimentRecord[] = [
  {
    ...base("sent-managed-youth-midc", ["src-field-reports"], 60),
    entityType: "community",
    entityId: "comm-youth",
    segment: "Youth",
    score: 68,
    previousScore: 61,
    trend: "Up",
    period: "2026-06",
    sentimentTitle: "MIDC youth sentiment improved after listening circle",
    sentimentType: "visit_observation",
    relatedEntityType: "visit_record",
    relatedEntityId: "visit-midc-youth-listening",
    villageId: "v-sinnar-town",
    boothId: "booth-midc-001",
    communityId: "comm-youth",
    sentimentDirection: "positive",
    description: "Youth participants responded positively to issue-first listening.",
    observedBy: "owner-youth-desk",
    dateObserved: "2026-06-10",
    sourceType: "field_report",
    approvalStatus: "pending_review",
    evidenceIds: ["ev-visit-youth-notes"]
  },
  {
    ...base("sent-managed-musalgaon-risk", ["src-field-reports"], 44),
    entityType: "village",
    entityId: "v-musalgaon",
    segment: "Musalgaon",
    score: 47,
    previousScore: 48,
    trend: "Down",
    period: "2026-06",
    sentimentTitle: "Musalgaon operational strain lowered field mood",
    sentimentType: "ownership_observation",
    relatedEntityType: "ownership_record",
    relatedEntityId: "own-v-musalgaon",
    villageId: "v-musalgaon",
    boothId: "booth-musalgaon-001",
    communityId: "comm-farmers",
    sentimentDirection: "negative",
    description: "Volunteer feedback indicates frustration due delayed follow-up and owner overload.",
    observedBy: "owner-war-room-lead",
    dateObserved: "2026-06-11",
    sourceType: "field_report",
    approvalStatus: "changes_requested",
    evidenceIds: ["ev-visit-musalgaon-followup"]
  }
];

export const importBatches: ImportBatch[] = [
  {
    ...base("import-voters-starter", ["src-field-reports"], 50),
    importTitle: "Voter starter CSV import",
    entityType: "Voters",
    fileName: "sinnar_voter_starter_template.csv",
    uploadedBy: "Data Operations",
    uploadedAt: "2026-06-12T08:40:00+05:30",
    totalRows: 250,
    validRows: 212,
    invalidRows: 22,
    duplicateRows: 16,
    status: "ready_for_review",
    sourceId: "src-field-reports",
    approvalStatus: "pending_review",
    rollbackAvailable: true,
    evidenceIds: [],
    mappingSummary: "Mapped voterName, villageId, boothId, supportStatus, relationshipOwnerId.",
    validationSummary: "Missing booth links and duplicate voter IDs need review."
  },
  {
    ...base("import-households-devpur", ["src-field-reports"], 38),
    importTitle: "Devpur household ownership import",
    entityType: "Households",
    fileName: "devpur_household_mapping.csv",
    uploadedBy: "War Room",
    uploadedAt: "2026-06-12T08:45:00+05:30",
    totalRows: 60,
    validRows: 44,
    invalidRows: 10,
    duplicateRows: 6,
    status: "pending_approval",
    sourceId: "src-field-reports",
    approvalStatus: "pending_review",
    rollbackAvailable: true,
    evidenceIds: [],
    mappingSummary: "Mapped householdName, villageId, communityIds, relationshipOwnerId.",
    validationSummary: "Unassigned owners require approval before import."
  }
];
